services:
  postgresql:
    container_name: maw-catalyst-db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=medaware
      - POSTGRES_USER=catalyst
      - POSTGRES_DB=catalystdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
  minio:
    container_name: maw-minio
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=catalyst
      - MINIO_ROOT_PASSWORD=medaware
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres-data:
  minio-data:
